export const LOYALTY_TRANSACTION_STATUS = {
  INITIATED: "INITIATED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  REVIEW: "REVIEW",
  CALCULATE: "CALCULATE",
  REJECTED: "REJECTED"
};

export const LOYALTY_LEDGER_TYPE = {
  ISSUE: "ISSUE",
  REDUCE: "REDUCE",
  BLOCK: "BLOCK",
  UNBLOCK: "UNBLOCK"
};

export enum ExpiryUnit {
  HOUR = "HOUR",
  DAY = "DAY",
  MONTH = "MONTH",
  YEAR = "YEAR"
}

export const CURRENCY_CODE = {
  DEFAULT: "DEFAULT"
};

export const LOYALTY_ATTRIBUTE_ENTITY_NAME = "Loyalty";

export const LOYALTY_ACTION_TYPE = {
  EARN_ACTION: "EARN_ACTION",
  BURN_ACTION: "BURN_ACTION",
  ISSUANCE_INPUT: "ISSUANCE_INPUT",
  EARN_BURN_ACTION: "EARN_BURN_ACTION",
  LOYALTY_ENABLE_ACTION: "LOYALTY_ENABLE_ACTION",
  LOYALTY_TRANSACTION_REVIEW: "LOYALTY_TRANSACTION_REVIEW"
};

export const JSON_SCHEMA = {
  EARNABLE_BURNABLE_POINTS: "EARNABLE_BURNABLE_POINTS",
  PROCESS_LOYALTY_ISSUANCE: "PROCESS_LOYALTY_ISSUANCE",
  PROCESS_LOYALTY_REDMPTION: "PROCESS_LOYALTY_REDMPTION",
  CREATE_OR_UPDATE_LOYALTY_TRANSACTION: "CREATE_OR_UPDATE_LOYALTY_TRANSACTION"
};

export const LOYALTY_PROGRAM_TYPE = {
  CASHBACK: "CASHBACK",
  PERCENTAGE_OF_TOTAL_AMOUNT: "PERCENTAGE_OF_TOTAL_AMOUNT"
};

export const LOYALTY_PROGRAM = {
  TRANSACTION: "TRANSACTION"
};

export const ROUNDING = {
  MODE: "HALF_UP",
  PRECISION: 0
};

export const RULE_LEVEL = {
  LOYALTY: "LOYALTY"
};
export const RULE_TYPE = {
  LOYALTY_TRANSACTION_EARN_LIMIT: "LOYALTY_TRANSACTION_EARN_LIMIT",
  LOYALTY_TRANSACTION_BURN_LIMIT: "LOYALTY_TRANSACTION_BURN_LIMIT",
  LOYALTY_SCHEDULED_DATE_TIME: "LOYALTY_SCHEDULED_DATE_TIME",
  ALLOW_PRODUCT_VALIDATION: "ALLOW_PRODUCT_VALIDATION"
};

export const ORDER_CHANNEL = {
  LOYALTY_TRANSACTION_EARN_ORDER_CHANNEL:
    "LOYALTY_TRANSACTION_EARN_ORDER_CHANNEL",
  LOYALTY_TRANSACTION_BURN_ORDER_CHANNEL:
    "LOYALTY_TRANSACTION_BURN_ORDER_CHANNEL"
};

export const ORDER_TYPE = {
  LOYALTY_TRANSACTION_EARN_ORDER_TYPE: "LOYALTY_TRANSACTION_EARN_ORDER_TYPE",
  LOYALTY_TRANSACTION_BURN_ORDER_TYPE: "LOYALTY_TRANSACTION_BURN_ORDER_TYPE"
};

export const TIME_FORMAT = {
  HH_MM_SS: "HH:mm:ss"
};

export const SCHEDULE_TIME_SLOT = {
  NIGHT_IN_TIME: "21:00:00",
  NIGHT_OUT_TIME: "23:59:59",
  MORN_IN_TIME: "00:00:00",
  MORN_OUT_TIME: "07:59:59"
};

export const EXPIRY_COMMUNICATION_EVENT_TYPE = {
  EXPIRY_REMINDER: "EXPIRY_REMINDER",
  EXPIRY: "EXPIRY"
};

export const WEBHOOK_CALL_TYPE = {
  INSERT: "INSERT",
  HOOK: "HOOK"
};

export const COLLECTIONS_ENTITY_TYPE = {
  STORE: "STORE",
  CUSTOMER: "CUSTOMER",
  PRODUCT: "PRODUCT"
};

export const COLLECTIONS_TYPE = {
  STATIC: "STATIC",
  DYNAMIC : "DYNAMIC"
};

export const ENTITY_NAME_MAPPING = {
  STORE: "Store",
  CUSTOMER: "Customer",
  PRODUCT: "Product"
};

export const ENTITY_QUERY_FIELD_MAPPING = {
  STORE: "externalStoreId",
  CUSTOMER: "externalCustomerId",
  PRODUCT: "externalProductId"
};

export const APPLICATION_METHOD = {
  EXCLUSIVE: "EXCLUSIVE",
  SEQUENTIAL: "SEQUENTIAL",
  ALWAYS: "ALWAYS"
};

export const VALID_STATUS_FOR_FYND = [
  "handed_over_to_customer",
  "delivery_done"
];

export const CUSTOMER_QUERY_PARAMS = {
  EMAIL: "email",
  MOBILE: "mobile"
};
