export enum POLICY_TYPE {
  "UI" = "UI",
  "ENTITY" = "ENTITY"
}

export enum POLICY_EFFECT {
  "ALLOW" = "ALLOW",
  "DENY" = "DENY"
}

export enum POLICY_ACCESS_LEVEL {
  "OWN" = "OWN",
  "ALL" = "ALL"
}

export enum POLICY_RESOURCES_CONSOLE {
  "REFINEX_CONSOLE" = "REFINEX_CONSOLE",
  "DOWNLOAD_EVENTS" = "DOWNLOAD_EVENTS",
  "DOWNLOAD_CUSTOMERS" = "DOWNLOAD_CUSTOMERS",
  "SETTINGS_GLOBAL" = "SETTINGS_GLOBAL",
  "SETTINGS_NEARX" = "SETTINGS_NEARX",
  "UPLOAD_PLACES" = "UPLOAD_PLACES",
  "ACCEPT_ORDER" = "ACCEPT_ORDER",
  "REJECT_ORDER" = "REJECT_ORDER",
  "DOWNLOAD_REPORTS" = "DOWNLOAD_REPORTS"
}

export enum POLICY_RESOURCES_ENTITY {
  "ORGANIZATION" = "ORGANIZATION",
  "USER" = "USER",
  "APPLICATION" = "APPLICATION",
  "STORE" = "STORE",
  "ROLE" = "ROLE",
  "CATALOG" = "CATALOG",
  "CATEGORY" = "CATEGORY",
  "PRODUCT" = "PRODUCT",
  "WEBHOOKS" = "WEBHOOKS",
  "EVENTS" = "EVENTS",
  "PLACES" = "PLACES",
  "CUSTOMER" = "CUSTOMER",
  "CUSTOMER_DEVICE" = "CUSTOMER_DEVICE",
  "FEEDBACK_CATEGORY" = "FEEDBACK_CATEGORY",
  "FEEDBACK_FORM" = "FEEDBACK_FORM",
  "FEEDBACK_RESPONSE" = "FEEDBACK_RESPONSE",
  "FEEDBACK_QUESTION" = "FEEDBACK_QUESTION",
  "FEEDBACK_CHOICE" = "FEEDBACK_CHOICE",
  "APIKEY" = "APIKEY",
  "ACTION" = "ACTION",
  "ACTION_DEFNITION" = "ACTION_DEFNITION",
  "AUDIENCE" = "AUDIENCE",
  "BUSINESS_RULE" = "BUSINESS_RULE",
  "CAMPAIGN" = "CAMPAIGN",
  "COMMUNICATION" = "COMMUNICATION",
  "ENTITY_EXTEND" = "ENTITY_EXTEND",
  "EVENT" = "EVENT",
  "FILE_SYSTEM" = "FILE_SYSTEM",
  "MEMBER" = "MEMBER",
  "METRIC" = "METRIC",
  "METRIC_FILTER" = "METRIC_FILTER",
  "POLICY" = "POLICY",
  "RULE" = "RULE",
  "SEGMENT" = "SEGMENT",
  "SESSION" = "SESSION",
  "WORKFLOW" = "WORKFLOW",
  "REPORT_CONFIG" = "REPORT_CONFIG",
  "REPORTS" = "REPORTS",
  "FILE" = "FILE",
  "CUSTOMER_FEEDBACK" = "CUSTOMER_FEEDBACK",
  "TAXTYPE" = "TAXTYPE",
  "STOREFORMAT" = "STOREFORMAT",
  "TAG" = "TAG",
  "COLLECTION" = "COLLECTION",
  "CHANNEL" = "CHANNEL",
  "CHARGETYPE" = "CHARGETYPE",
  "PARTNER" = "PARTNER",
  "DELIVERY" = "DELIVERY",
  "PAYMENT" = "PAYMENT",
  "STAFF" = "STAFF",
  "BANK_ACCOUNT" = "BANK_ACCOUNT",
  "ORDER" = "ORDER",
  "LEGAL_INFO" = "LEGAL_INFO",
  "USER_PASSWORD_UPDATE" = "USER_PASSWORD_UPDATE",
  "DISCOUNT_TYPE" = "DISCOUNT_TYPE",
  "MENU_TIMING" = "MENU_TIMING",
  "COLLECTIONS" = "COLLECTIONS",
  "LOYALTY_PROGRAM" = "LOYALTY_PROGRAM"
}

export enum POLICY_PERMISSION_CONSOLE {
  "VIEW" = "VIEW",
  "MODIFY" = "MODIFY"
}

export enum POLICY_PERMISSION_ENTITY {
  "CREATE" = "CREATE",
  "READ" = "READ",
  "UPDATE" = "UPDATE",
  "DELETE" = "DELETE",
  "LIST" = "LIST",
  "SEARCH" = "SEARCH",
  "EXECUTE" = "EXECUTE"
}

export enum ROLE_NAME {
  "ADMIN" = "ADMIN",
  "MANAGER" = "MANAGER",
  "USER" = "USER"
}